# Generated by Django 5.0.8 on 2024-11-05 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stakeholder', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chickbatch',
            name='batch_status',
            field=models.CharField(choices=[('active', 'Active'), ('completed', 'Completed')], default='active', help_text='Current status of the batch', max_length=10),
        ),
    ]
