# Generated by Django 5.0.8 on 2025-01-18 09:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stakeholder', '0001_initial'),
        ('user', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='chickbatch',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chick_batches', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='chicksupply',
            name='batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chick_supplies', to='stakeholder.chickbatch'),
        ),
        migrations.AddField(
            model_name='chicksupply',
            name='stakeholder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chick_supplies', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dailydata',
            name='batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_data', to='stakeholder.chickbatch'),
        ),
        migrations.AddField(
            model_name='dailydata',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_data_records', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='feedmonitoring',
            name='batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stakeholder.chickbatch'),
        ),
        migrations.AddField(
            model_name='vaccinationschedule',
            name='batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vaccination_schedules', to='stakeholder.chickbatch'),
        ),
        migrations.AddField(
            model_name='vaccinationschedule',
            name='vaccine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.vaccine'),
        ),
        migrations.AlterUniqueTogether(
            name='dailydata',
            unique_together={('batch', 'date')},
        ),
        migrations.AlterUniqueTogether(
            name='feedmonitoring',
            unique_together={('batch', 'date')},
        ),
    ]
