# Generated by Django 5.0.8 on 2024-10-16 14:56

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stakeholder', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('alive_count', models.IntegerField()),
                ('sick_chicks', models.IntegerField(default=0)),
                ('weight_gain', models.FloatField()),
                ('feed_uplifted', models.FloatField()),
                ('water_consumption', models.FloatField()),
                ('temperature', models.FloatField()),
                ('mortality_count', models.IntegerField(default=0)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_data', to='stakeholder.chickbatch')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_data_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('batch', 'date')},
            },
        ),
    ]
