# Generated by Django 5.0.8 on 2025-02-28 07:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stakeholder', '0001_initial'),
        ('user', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='chickbatch',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='farm_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='chicksupply',
            name='batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chick_supplies', to='stakeholder.chickbatch'),
        ),
        migrations.AddField(
            model_name='chicksupply',
            name='stakeholder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chick_supplies', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='comment',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dailydata',
            name='batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_data', to='stakeholder.chickbatch'),
        ),
        migrations.AddField(
            model_name='dailydata',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_data_records', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dailyfeedconsumption',
            name='batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_feed_records', to='stakeholder.chickbatch'),
        ),
        migrations.AddField(
            model_name='dailyfeedconsumption',
            name='recorded_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='diseaseanalysis',
            name='batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disease_analyses', to='stakeholder.chickbatch'),
        ),
        migrations.AddField(
            model_name='diseaseanalysis',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disease_analyses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='farm',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='farms', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='chickbatch',
            name='farm',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chick_batches', to='stakeholder.farm'),
        ),
        migrations.AddField(
            model_name='feedassignment',
            name='batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feed_assignments', to='stakeholder.chickbatch'),
        ),
        migrations.AddField(
            model_name='feedassignment',
            name='feed_stock',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.feedstock'),
        ),
        migrations.AddField(
            model_name='dailyfeedconsumption',
            name='feed_assignment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_consumptions', to='stakeholder.feedassignment'),
        ),
        migrations.AddField(
            model_name='feedcalculator',
            name='batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stakeholder.chickbatch'),
        ),
        migrations.AddField(
            model_name='feedmonitoring',
            name='batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stakeholder.chickbatch'),
        ),
        migrations.AddField(
            model_name='growthprediction',
            name='batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stakeholder.chickbatch'),
        ),
        migrations.AddField(
            model_name='post',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='stakeholder.post'),
        ),
        migrations.AddField(
            model_name='successstory',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='success_stories', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='vaccinationauditlog',
            name='performed_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='vaccinationschedule',
            name='assigned_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_vaccinations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='vaccinationschedule',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assigned_vaccinations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='vaccinationschedule',
            name='batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vaccination_schedules', to='stakeholder.chickbatch'),
        ),
        migrations.AddField(
            model_name='vaccinationschedule',
            name='vaccine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.vaccine'),
        ),
        migrations.AddField(
            model_name='vaccinationauditlog',
            name='vaccination',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stakeholder.vaccinationschedule'),
        ),
        migrations.AlterUniqueTogether(
            name='dailydata',
            unique_together={('batch', 'date')},
        ),
        migrations.AlterUniqueTogether(
            name='feedassignment',
            unique_together={('batch', 'week_number')},
        ),
        migrations.AlterUniqueTogether(
            name='dailyfeedconsumption',
            unique_together={('batch', 'date')},
        ),
        migrations.AlterUniqueTogether(
            name='feedmonitoring',
            unique_together={('batch', 'date')},
        ),
        migrations.AlterUniqueTogether(
            name='vaccinationschedule',
            unique_together={('batch', 'vaccine', 'vaccination_date', 'status')},
        ),
    ]
