# Generated by Django 5.1.5 on 2025-01-18 13:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stakeholder", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Farm",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("location", models.CharField(max_length=255)),
                (
                    "farm_image",
                    models.ImageField(blank=True, null=True, upload_to="images/"),
                ),
                ("length", models.FloatField(blank=True, default=None, null=True)),
                ("breadth", models.FloatField(blank=True, default=None, null=True)),
                (
                    "size",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("established_date", models.DateField(blank=True, null=True)),
                (
                    "coopcapacity",
                    models.IntegerField(blank=True, default=None, null=True),
                ),
                ("is_recommended", models.BooleanField(default=False)),
                ("latitude", models.FloatField(blank=True, null=True)),
                ("longitude", models.FloatField(blank=True, null=True)),
                (
                    "plan_file",
                    models.FileField(blank=True, null=True, upload_to="farm_plan/"),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="farms",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
