# Generated by Django 5.0.8 on 2024-10-18 05:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stakeholder', '0002_dailydata'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chickbatch',
            old_name='chick_count',
            new_name='initial_chick_count',
        ),
    ]
