# Generated by Django 5.0.8 on 2025-03-01 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stakeholder', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailydata',
            name='feed_uplifted',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Number of feed sacks consumed', max_digits=5),
        ),
    ]
