# Generated by Django 5.0.8 on 2024-10-05 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stakeholder', '0003_feedrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedrequest',
            name='feed_type',
            field=models.CharField(choices=[('Pre-Starter', 'Pre-Starter'), ('Starter', 'Starter'), ('Finisher', 'Finisher')], default='Starter', max_length=20),
        ),
    ]
