# Generated by Django 5.0.8 on 2025-03-01 02:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stakeholder', '0003_alter_dailydata_feed_uplifted'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=50)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stakeholder.chickbatch')),
                ('feed_assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stakeholder.feedassignment')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
