# Generated by Django 5.0.8 on 2024-10-18 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stakeholder', '0003_rename_chick_count_chickbatch_initial_chick_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='chickbatch',
            name='batch_status',
            field=models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('inactive', 'Inactive'), ('pending', 'Pending')], default='active', max_length=10),
        ),
    ]
