# Generated by Django 5.0.8 on 2024-10-05 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stakeholder', '0004_feedrequest_feed_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedrequest',
            old_name='feed_quantity',
            new_name='feed_amount',
        ),
    ]
