# Generated by Django 5.1.5 on 2025-01-18 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stakeholder", "0004_alter_farm_farm_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="farm",
            name="certification_file",
            field=models.FileField(blank=True, null=True, upload_to="certifications/"),
        ),
        migrations.AddField(
            model_name="farm",
            name="certification_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("ORGANIC", "Organic Certified"),
                    ("STANDARD", "Standard"),
                    ("PREMIUM", "Premium Quality"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="farm",
            name="pollution_certificate",
            field=models.FileField(blank=True, null=True, upload_to="certificates/"),
        ),
    ]
