# Generated by Django 5.0.8 on 2024-10-19 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stakeholder', '0004_chickbatch_batch_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailydata',
            name='feed_forecast',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='dailydata',
            name='feed_remaining',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='dailydata',
            name='feed_wastage',
            field=models.FloatField(default=0.0),
        ),
    ]
