# Generated by Django 5.1.5 on 2025-01-19 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "stakeholder",
            "0005_farm_certification_file_farm_certification_type_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="farm",
            name="address",
            field=models.CharField(default="hello", max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="farm",
            name="expiry_date",
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
