# Generated by Django 5.0.8 on 2024-10-19 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stakeholder', '0005_dailydata_feed_forecast_dailydata_feed_remaining_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dailydata',
            name='feed_forecast',
        ),
        migrations.RemoveField(
            model_name='dailydata',
            name='feed_remaining',
        ),
        migrations.RemoveField(
            model_name='dailydata',
            name='feed_wastage',
        ),
    ]
