# Generated by Django 5.0.8 on 2025-03-01 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stakeholder', '0006_remove_feednotification_week_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='feednotification',
            name='week_number1',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
