# Generated by Django 5.1.5 on 2025-01-19 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stakeholder", "0006_farm_address_farm_expiry_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="farm",
            name="address",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
