# Generated by Django 5.0.8 on 2024-10-19 07:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stakeholder', '0006_remove_dailydata_feed_forecast_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='dailydata',
            unique_together=set(),
        ),
        migrations.CreateModel(
            name='FeedMonitoring',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('feed_consumed', models.FloatField(default=0.0)),
                ('feed_forecast', models.FloatField(default=0.0)),
                ('feed_wastage', models.FloatField(default=0.0)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stakeholder.chickbatch')),
            ],
            options={
                'unique_together': {('batch', 'date')},
            },
        ),
    ]
