# Generated by Django 5.1.5 on 2025-01-19 04:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("stakeholder", "0007_alter_farm_address"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="farm",
            name="location",
        ),
    ]
