# Generated by Django 5.0.8 on 2024-10-20 04:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stakeholder', '0007_alter_dailydata_unique_together_feedmonitoring'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feedmonitoring',
            options={'verbose_name': 'Feed Monitoring', 'verbose_name_plural': 'Feed Monitoring'},
        ),
        migrations.AddField(
            model_name='feedmonitoring',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
