# Generated by Django 5.1.5 on 2025-01-19 11:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stakeholder", "0008_remove_farm_location"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="chickbatch",
            name="farm",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="chick_batches",
                to="stakeholder.farm",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="chickbatch",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="farm_user",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
