# Generated by Django 5.0.8 on 2024-10-20 04:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stakeholder', '0008_alter_feedmonitoring_options_feedmonitoring_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedmonitoring',
            name='owner',
        ),
    ]
