# Generated by Django 5.0.8 on 2025-03-01 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stakeholder', '0009_dailydata_actual_fcr_dailydata_target_fcr'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dailydata',
            name='actual_fcr',
        ),
        migrations.RemoveField(
            model_name='dailydata',
            name='target_fcr',
        ),
        migrations.AddField(
            model_name='chickbatch',
            name='admin_revenue',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='chickbatch',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='chickbatch',
            name='stakeholder_payment',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
