# Generated by Django 5.0.8 on 2024-10-20 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stakeholder', '0009_remove_feedmonitoring_owner'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='dailydata',
            unique_together={('batch', 'date')},
        ),
    ]
