# Generated by Django 5.0.8 on 2025-03-01 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stakeholder', '0010_remove_dailydata_actual_fcr_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chickbatch',
            name='actual_fcr',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='chickbatch',
            name='target_fcr',
            field=models.DecimalField(decimal_places=2, default=1.5, max_digits=4),
        ),
    ]
