# Generated by Django 5.0.8 on 2025-01-29 06:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stakeholder', '0011_successstory'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChickHealthAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='chick_health_images/')),
                ('analyzed_date', models.DateTimeField(auto_now_add=True)),
                ('is_healthy', models.BooleanField()),
                ('status', models.CharField(max_length=100)),
                ('confidence_score', models.FloatField()),
                ('feather_quality', models.FloatField()),
                ('color_health', models.FloatField()),
                ('overall_condition', models.FloatField()),
                ('recommendations', models.JSONField()),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_analyses', to='stakeholder.chickbatch')),
            ],
            options={
                'ordering': ['-analyzed_date'],
            },
        ),
    ]
