# Generated by Django 5.0.8 on 2024-10-20 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stakeholder', '0011_alter_dailydata_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='dailydata',
            unique_together={('batch', 'date')},
        ),
    ]
