# Generated by Django 5.0.8 on 2025-02-01 05:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stakeholder', '0012_chickhealthanalysis'),
    ]

    operations = [
        migrations.CreateModel(
            name='FarmerChat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receiver_farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_farmer_chats', to='stakeholder.farm')),
                ('sender_farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_farmer_chats', to='stakeholder.farm')),
            ],
        ),
    ]
