# Generated by Django 5.0.8 on 2024-10-20 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stakeholder', '0012_alter_dailydata_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chickbatch',
            name='batch_status',
            field=models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('uplifted', 'Uplifted'), ('terminated', 'Terminated')], default='active', max_length=10),
        ),
    ]
