# Generated by Django 5.0.8 on 2025-03-03 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stakeholder', '0012_stakeholderpayment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stakeholderpayment',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('bank_transfer', 'Bank Transfer'), ('upi', 'UPI'), ('cash', 'Cash'), ('check', 'Check')], max_length=20, null=True),
        ),
    ]
