# Generated by Django 5.0.8 on 2025-03-05 04:01

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stakeholder', '0013_alter_stakeholderpayment_payment_method'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='diseaseanalysis',
            options={'ordering': ['-analyzed_date']},
        ),
        migrations.RemoveField(
            model_name='diseaseanalysis',
            name='behavior_notes',
        ),
        migrations.RemoveField(
            model_name='diseaseanalysis',
            name='confidence_level',
        ),
        migrations.RemoveField(
            model_name='diseaseanalysis',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='diseaseanalysis',
            name='follow_up_date',
        ),
        migrations.RemoveField(
            model_name='diseaseanalysis',
            name='is_critical',
        ),
        migrations.RemoveField(
            model_name='diseaseanalysis',
            name='needs_review',
        ),
        migrations.RemoveField(
            model_name='diseaseanalysis',
            name='recommendations',
        ),
        migrations.RemoveField(
            model_name='diseaseanalysis',
            name='temperature',
        ),
        migrations.RemoveField(
            model_name='diseaseanalysis',
            name='veterinary_referral',
        ),
        migrations.RemoveField(
            model_name='diseaseanalysis',
            name='warning_message',
        ),
        migrations.AddField(
            model_name='diseaseanalysis',
            name='all_probabilities',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='diseaseanalysis',
            name='correct_label',
            field=models.CharField(blank=True, choices=[('Healthy', 'Healthy'), ('Coccidiosis', 'Coccidiosis'), ('New Castle Disease', 'New Castle Disease'), ('Salmonella', 'Salmonella')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='diseaseanalysis',
            name='feedback_provided',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='diseaseanalysis',
            name='analyzed_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='diseaseanalysis',
            name='confidence_score',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='diseaseanalysis',
            name='image',
            field=models.ImageField(upload_to='disease_analysis/'),
        ),
        migrations.AlterField(
            model_name='diseaseanalysis',
            name='predicted_disease',
            field=models.CharField(choices=[('Healthy', 'Healthy'), ('Coccidiosis', 'Coccidiosis'), ('New Castle Disease', 'New Castle Disease'), ('Salmonella', 'Salmonella')], max_length=100),
        ),
        migrations.AlterField(
            model_name='diseaseanalysis',
            name='symptoms_detected',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterModelTable(
            name='diseaseanalysis',
            table=None,
        ),
    ]
