# Generated by Django 5.0.8 on 2024-10-22 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stakeholder', '0013_alter_chickbatch_batch_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='chickbatch',
            name='duration',
            field=models.IntegerField(default=40),
        ),
    ]
