# Generated by Django 5.0.8 on 2025-02-01 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stakeholder', '0013_farmerchat'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FarmerChat',
        ),
    ]
