# Generated by Django 5.0.8 on 2025-03-09 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stakeholder', '0014_alter_diseaseanalysis_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='diseaseanalysis',
            name='severity',
            field=models.CharField(default='Unknown', max_length=50),
        ),
    ]
