# Generated by Django 5.0.8 on 2025-02-02 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stakeholder', '0015_post_category_alter_post_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='chickbatch',
            name='completion_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chickbatch',
            name='reward_claimed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='chickbatch',
            name='reward_claimed_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
