# Generated by Django 5.0.8 on 2025-03-09 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stakeholder', '0015_diseaseanalysis_severity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diseaseanalysis',
            name='severity',
            field=models.CharField(default='Low', max_length=50),
        ),
    ]
