# Generated by Django 5.0.8 on 2025-02-03 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stakeholder', '0016_chickbatch_completion_date_chickbatch_reward_claimed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chickbatch',
            name='reward_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Reward amount based on FCR performance', max_digits=10),
        ),
        migrations.AddField(
            model_name='chickbatch',
            name='reward_status',
            field=models.BooleanField(default=False),
        ),
    ]
