# Generated by Django 5.0.8 on 2025-02-06 05:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stakeholder', '0017_chickbatch_reward_amount_chickbatch_reward_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chickhealthanalysis',
            old_name='image',
            new_name='images',
        ),
    ]
