# Generated by Django 5.0.8 on 2025-02-06 05:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stakeholder', '0018_rename_image_chickhealthanalysis_images'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chickhealthanalysis',
            old_name='images',
            new_name='image',
        ),
    ]
