# Generated by Django 5.0.8 on 2025-02-06 05:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stakeholder', '0019_rename_images_chickhealthanalysis_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ChickHealthAnalysis',
        ),
    ]
