# Generated by Django 5.0.8 on 2025-02-06 05:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stakeholder', '0020_delete_chickhealthanalysis'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DiseaseAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='Upload image of the chicken for analysis', upload_to='disease_analysis/')),
                ('analyzed_date', models.DateTimeField(auto_now_add=True)),
                ('predicted_disease', models.CharField(choices=[('healthy', 'Healthy'), ('coccidiosis', 'Coccidiosis'), ('salmonella', 'Salmonella'), ('aspergillosis', 'Aspergillosis'), ('colibacillosis', 'Colibacillosis'), ('marek', "Marek's Disease"), ('newcastle', 'Newcastle Disease'), ('infectious_bronchitis', 'Infectious Bronchitis')], help_text='Predicted disease based on image analysis', max_length=50)),
                ('confidence_score', models.FloatField(help_text='Confidence score of the prediction (0-1)')),
                ('symptoms_detected', models.JSONField(default=list, help_text='List of symptoms detected in the analysis')),
                ('temperature', models.FloatField(blank=True, help_text='Body temperature if measured', null=True)),
                ('behavior_notes', models.TextField(blank=True, help_text='Notes about chicken behavior')),
                ('recommendations', models.JSONField(default=dict, help_text='Treatment recommendations and precautions')),
                ('veterinary_referral', models.BooleanField(default=False, help_text='Whether veterinary consultation is recommended')),
                ('is_critical', models.BooleanField(default=False, help_text='Indicates if immediate attention is required')),
                ('follow_up_date', models.DateField(blank=True, help_text='Recommended date for follow-up analysis', null=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disease_analyses', to='stakeholder.chickbatch')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disease_analyses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Disease Analysis',
                'verbose_name_plural': 'Disease Analyses',
                'db_table': 'stakeholder_diseaseanalysis',
                'ordering': ['-analyzed_date'],
            },
        ),
    ]
