# Generated by Django 5.0.8 on 2025-02-10 09:10

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stakeholder', '0022_chickbatch_batch_uuid_chickbatch_qr_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chickbatch',
            name='batch_uuid',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
    ]
