# Generated by Django 5.0.8 on 2025-02-12 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stakeholder', '0023_alter_chickbatch_batch_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='diseaseanalysis',
            name='confidence_level',
            field=models.CharField(choices=[('High', 'High'), ('Medium', 'Medium'), ('Low', 'Low'), ('Error', 'Error')], default=0, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='diseaseanalysis',
            name='needs_review',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='diseaseanalysis',
            name='warning_message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
