# Generated by Django 5.0.8 on 2025-02-12 09:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stakeholder', '0024_diseaseanalysis_confidence_level_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedCalculator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_chicks', models.IntegerField()),
                ('calculated_feed_kg', models.FloatField()),
                ('calculated_sacks', models.FloatField()),
                ('safety_margin_sacks', models.FloatField()),
                ('starter_feed_sacks', models.FloatField()),
                ('grower_feed_sacks', models.FloatField()),
                ('finisher_feed_sacks', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stakeholder.chickbatch')),
            ],
        ),
    ]
