# Generated by Django 5.0.8 on 2025-02-12 17:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stakeholder', '0025_feedcalculator'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_number', models.IntegerField()),
                ('sacks_assigned', models.IntegerField()),
                ('cost_per_sack', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('assigned_date', models.DateTimeField(auto_now_add=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stakeholder.chickbatch')),
            ],
            options={
                'ordering': ['-assigned_date'],
            },
        ),
    ]
