# Generated by Django 5.0.8 on 2025-02-13 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stakeholder', '0026_feedassignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='chickbatch',
            name='assigned_feed_sacks',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='chickbatch',
            name='remaining_feed_sacks',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='chickbatch',
            name='total_feed_sacks',
            field=models.IntegerField(default=0),
        ),
    ]
