# Generated by Django 5.0.8 on 2025-02-13 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stakeholder', '0027_chickbatch_assigned_feed_sacks_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chickbatch',
            name='finisher_feed_consumed',
            field=models.PositiveIntegerField(default=0, help_text='Number of finisher feed sacks consumed'),
        ),
        migrations.AddField(
            model_name='chickbatch',
            name='finisher_feed_sacks',
            field=models.PositiveIntegerField(default=0, help_text='Number of finisher feed sacks assigned (36+ days)'),
        ),
        migrations.AddField(
            model_name='chickbatch',
            name='grower_feed_consumed',
            field=models.PositiveIntegerField(default=0, help_text='Number of grower feed sacks consumed'),
        ),
        migrations.AddField(
            model_name='chickbatch',
            name='grower_feed_sacks',
            field=models.PositiveIntegerField(default=0, help_text='Number of grower feed sacks assigned (22-35 days)'),
        ),
        migrations.AddField(
            model_name='chickbatch',
            name='starter_feed_consumed',
            field=models.PositiveIntegerField(default=0, help_text='Number of starter feed sacks consumed'),
        ),
        migrations.AddField(
            model_name='chickbatch',
            name='starter_feed_sacks',
            field=models.PositiveIntegerField(default=0, help_text='Number of starter feed sacks assigned (0-21 days)'),
        ),
        migrations.AlterField(
            model_name='chickbatch',
            name='total_feed_sacks',
            field=models.PositiveIntegerField(default=0, help_text='Total number of feed sacks assigned'),
        ),
    ]
