# Generated by Django 5.0.8 on 2025-02-13 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stakeholder', '0028_chickbatch_finisher_feed_consumed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chickbatch',
            name='finisher_feed_consumed',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='chickbatch',
            name='finisher_feed_sacks',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='chickbatch',
            name='grower_feed_consumed',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='chickbatch',
            name='grower_feed_sacks',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='chickbatch',
            name='starter_feed_consumed',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='chickbatch',
            name='starter_feed_sacks',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='chickbatch',
            name='total_feed_sacks',
            field=models.IntegerField(default=0),
        ),
    ]
