# Generated by Django 5.0.8 on 2025-02-14 04:42
import django.db.models.deletion
from django.db import migrations
from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('stakeholder', '0029_alter_chickbatch_finisher_feed_consumed_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_number', models.IntegerField()),
                ('feed_type', models.CharField(choices=[('Starter Feed', 'Starter Feed'), ('Grower Feed', 'Grower Feed'), ('Finisher Feed', 'Finisher Feed')], max_length=50)),
                ('sacks_assigned', models.IntegerField()),
                ('cost_per_sack', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('assigned_date', models.DateTimeField(auto_now_add=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stakeholder.chickbatch')),
                ('feed_stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.feedstock')),
            ],
            options={
                'db_table': 'feed_assignment',
                'unique_together': {('batch', 'week_number')},
            },
        ),
    ]
