# Generated by Django 5.0.8 on 2025-02-15 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stakeholder', '0030_auto_20250214_1012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chickbatch',
            name='starter_feed_sacks',
            field=models.IntegerField(default=0, help_text='Number of starter feed sacks assigned'),
        ),
        migrations.AlterField(
            model_name='feedassignment',
            name='total_cost',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
