# Generated by Django 5.0.8 on 2025-02-15 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stakeholder', '0031_alter_chickbatch_starter_feed_sacks_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chickbatch',
            name='current_feed_type',
            field=models.CharField(choices=[('Starter Feed', 'Starter Feed'), ('Grower Feed', 'Grower Feed'), ('Finisher Feed', 'Finisher Feed')], default='Starter Feed', max_length=50),
        ),
        migrations.AddField(
            model_name='chickbatch',
            name='feed_transition_notified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='chickbatch',
            name='last_feed_transition',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
