# Generated by Django 5.0.8 on 2025-02-15 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stakeholder', '0032_chickbatch_current_feed_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedassignment',
            name='acknowledgment_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='feedassignment',
            name='acknowledgment_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='feedassignment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('acknowledged', 'Acknowledged'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
    ]
