# Generated by Django 5.0.8 on 2025-02-15 10:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stakeholder', '0033_feedassignment_acknowledgment_date_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyFeedConsumption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('day_number', models.IntegerField()),
                ('morning_consumption', models.DecimalField(decimal_places=2, default=0, help_text='Number of sacks consumed in morning', max_digits=4)),
                ('evening_consumption', models.DecimalField(decimal_places=2, default=0, help_text='Number of sacks consumed in evening', max_digits=4)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_feed_records', to='stakeholder.chickbatch')),
                ('feed_assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_consumptions', to='stakeholder.feedassignment')),
                ('recorded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('batch', 'date')},
            },
        ),
    ]
