# Generated by Django 5.0.8 on 2025-02-16 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stakeholder', '0034_dailyfeedconsumption'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dailyfeedconsumption',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='feedassignment',
            name='total_cost',
        ),
        migrations.AlterField(
            model_name='dailyfeedconsumption',
            name='evening_consumption',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4),
        ),
        migrations.AlterField(
            model_name='dailyfeedconsumption',
            name='morning_consumption',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4),
        ),
    ]
