# Generated by Django 5.0.8 on 2025-02-18 02:40

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stakeholder', '0035_remove_dailyfeedconsumption_updated_at_and_more'),
        ('user', '0018_alter_vaccine_batch_number_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vaccinationschedule',
            options={'ordering': ['-vaccination_date']},
        ),
        migrations.AddField(
            model_name='vaccinationschedule',
            name='administration_photo',
            field=models.ImageField(blank=True, null=True, upload_to='vaccination_evidence/admin/'),
        ),
        migrations.AddField(
            model_name='vaccinationschedule',
            name='assigned_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_vaccinations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='vaccinationschedule',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assigned_vaccinations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='vaccinationschedule',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vaccinationschedule',
            name='farm_coordinates',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='vaccinationschedule',
            name='flock_photo',
            field=models.ImageField(blank=True, null=True, upload_to='vaccination_evidence/flocks/'),
        ),
        migrations.AddField(
            model_name='vaccinationschedule',
            name='humidity',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='vaccinationschedule',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='vaccinationschedule',
            name='qr_code',
            field=models.ImageField(blank=True, upload_to='vaccination_qr_codes/'),
        ),
        migrations.AddField(
            model_name='vaccinationschedule',
            name='rejection_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='vaccinationschedule',
            name='scan_coordinates',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='vaccinationschedule',
            name='status',
            field=models.CharField(choices=[('assigned', 'Assigned'), ('qr_scanned', 'QR Scanned'), ('evidence_uploaded', 'Evidence Uploaded'), ('administered', 'Administered'), ('verified', 'Verified'), ('rejected', 'Rejected')], default='assigned', max_length=20),
        ),
        migrations.AddField(
            model_name='vaccinationschedule',
            name='temperature',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='vaccinationschedule',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='vaccinationschedule',
            name='vaccine_vial_photo',
            field=models.ImageField(blank=True, null=True, upload_to='vaccination_evidence/vials/'),
        ),
        migrations.AddField(
            model_name='vaccinationschedule',
            name='verification_code',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='vaccinationschedule',
            unique_together={('batch', 'vaccine', 'vaccination_date')},
        ),
    ]
