# Generated by Django 5.0.8 on 2025-02-18 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stakeholder', '0037_vaccinationauditlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vaccinationschedule',
            name='verification_code',
            field=models.CharField(blank=True, default=1, max_length=20, unique=True),
            preserve_default=False,
        ),
    ]
