# Generated by Django 5.0.8 on 2025-02-18 10:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stakeholder', '0038_alter_vaccinationschedule_verification_code'),
        ('user', '0018_alter_vaccine_batch_number_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='vaccinationschedule',
            unique_together={('batch', 'vaccine', 'vaccination_date', 'status')},
        ),
        migrations.AddIndex(
            model_name='vaccinationschedule',
            index=models.Index(fields=['batch', 'vaccine', 'vaccination_date'], name='stakeholder_batch_i_c22589_idx'),
        ),
    ]
