# Generated by Django 5.0.8 on 2025-02-19 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stakeholder', '0039_alter_vaccinationschedule_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='vaccinationschedule',
            name='stakeholder_batch_i_c22589_idx',
        ),
    ]
