# Generated by Django 5.0.8 on 2025-02-22 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stakeholder', '0040_remove_vaccinationschedule_stakeholder_batch_i_c22589_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedassignment',
            name='is_late',
            field=models.BooleanField(default=False),
        ),
    ]
