# Generated by Django 5.0.8 on 2025-02-24 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stakeholder', '0041_feedassignment_is_late'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farm',
            name='coopcapacity',
            field=models.IntegerField(default=0),
        ),
    ]
