# Generated by Django 5.0.8 on 2025-02-24 17:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stakeholder', '0042_alter_farm_coopcapacity'),
    ]

    operations = [
        migrations.CreateModel(
            name='GrowthPrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('day_number', models.IntegerField()),
                ('feed_consumed', models.FloatField()),
                ('water_consumed', models.FloatField()),
                ('temperature', models.FloatField()),
                ('alive_count', models.IntegerField()),
                ('predicted_weight', models.FloatField()),
                ('actual_weight', models.FloatField(blank=True, null=True)),
                ('weight_difference', models.FloatField(blank=True, null=True)),
                ('growth_status', models.CharField(choices=[('On Track', 'On Track'), ('Under-Growing', 'Under-Growing'), ('Over-Growing', 'Over-Growing'), ('Pending', 'Pending Verification')], default='Pending', max_length=20)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stakeholder.chickbatch')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
