# Generated by Django 5.0.8 on 2025-02-26 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stakeholder', '0043_growthprediction'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedassignment',
            name='total_cost',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
