# Generated by Django 5.0.8 on 2025-02-28 07:27

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('one_kg_count', models.IntegerField(default=0, help_text='Number of 1 kg chickens ordered')),
                ('two_kg_count', models.IntegerField(default=0, help_text='Number of 2 kg chickens ordered')),
                ('three_kg_count', models.IntegerField(default=0, help_text='Number of 3 kg chickens ordered')),
                ('is_processed', models.BooleanField(default=False, help_text='True if fully dressed, False if live')),
                ('item_type', models.CharField(choices=[('live', 'Live'), ('processed', 'Processed')], default='live', help_text='Specify if the item is live or processed', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='HotelUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hotel_name', models.CharField(max_length=100)),
                ('expiry_date', models.DateField(blank=True, default=None, null=True)),
                ('hotel_license', models.FileField(blank=True, null=True, upload_to='hotel_licenses/')),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('one_kg_count', models.IntegerField(default=0, help_text='Number of 1 kg chickens ordered')),
                ('two_kg_count', models.IntegerField(default=0, help_text='Number of 2 kg chickens ordered')),
                ('three_kg_count', models.IntegerField(default=0, help_text='Number of 3 kg chickens ordered')),
                ('order_date', models.DateTimeField(auto_now_add=True)),
                ('delivery_date', models.DateField(blank=True, help_text='Expected delivery date', null=True)),
                ('price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total order price', max_digits=10)),
                ('payment_method', models.CharField(choices=[('cod', 'Cash On Delivery'), ('online', 'Online Transfer'), ('upi', 'UPI')], default='cod', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed')], default='pending', max_length=20)),
                ('delivery_option', models.CharField(choices=[('standard', 'Standard Delivery'), ('express', 'Express Delivery')], default='standard', max_length=10)),
                ('delivery_fee', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Fee based on delivery option', max_digits=6)),
            ],
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('loyalty_points', models.IntegerField(default=0)),
                ('membership_tier', models.CharField(choices=[('Silver', 'Silver'), ('Gold', 'Gold'), ('Platinum', 'Platinum')], default='Silver', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='WalletTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('transaction_type', models.CharField(choices=[('credit', 'Credit'), ('debit', 'Debit')], max_length=10)),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('payment_method', models.CharField(blank=True, choices=[('upi', 'UPI'), ('card', 'Credit/Debit Card'), ('netbanking', 'Net Banking')], max_length=20, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
