# Generated by Django 5.0.8 on 2025-01-18 09:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hoteldetails', '0001_initial'),
        ('stakeholder', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='cart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='hoteldetails.cart'),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='chick_batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stakeholder.chickbatch'),
        ),
        migrations.AddField(
            model_name='order',
            name='batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stakeholder.chickbatch'),
        ),
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
