# Generated by Django 5.1.5 on 2025-01-19 05:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hoteldetails", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="HotelUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("expiry_date", models.DateField(blank=True, default=None, null=True)),
                (
                    "hotel_license",
                    models.FileField(
                        blank=True, null=True, upload_to="hotel_licenses/"
                    ),
                ),
                ("address", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "hotel_owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hotel_users",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
