# Generated by Django 5.1.5 on 2025-01-19 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hoteldetails", "0003_hoteluser"),
    ]

    operations = [
        migrations.AddField(
            model_name="hoteluser",
            name="hotel_name",
            field=models.CharField(default="hrllo", max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="hoteluser",
            name="latitude",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="hoteluser",
            name="longitude",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
