# Generated by Django 5.0.8 on 2025-03-11 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hoteldetails', '0003_order_admin_notes_order_approved_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='current_latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='current_longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='last_location_update',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
