# Generated by Django 5.0.8 on 2025-03-11 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hoteldetails', '0004_order_current_latitude_order_current_longitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='transit_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('transit_to_hotel', 'Transit to Hotel'), ('out_for_delivery', 'Out for Delivery'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
    ]
