# Generated by Django 5.0.8 on 2025-03-13 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hoteldetails', '0005_order_transit_started_at_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='tracking_token',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
