# Generated by Django 5.0.8 on 2025-03-13 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hoteldetails', '0006_order_tracking_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='current_address',
            field=models.TextField(blank=True, null=True),
        ),
    ]
