# Generated by Django 5.0.8 on 2025-02-28 07:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='end_date',
            field=models.DateField(default=datetime.datetime(2026, 2, 28, 7, 28, 13, 932436, tzinfo=datetime.timezone.utc)),
        ),
    ]
