# Generated by Django 5.0.8 on 2024-10-15 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='plan_file',
            field=models.FileField(blank=True, null=True, upload_to='farm_plan/'),
        ),
    ]
