# Generated by Django 5.1.5 on 2025-01-18 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0002_remove_user_breadth_remove_user_coopcapacity_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="name",
        ),
    ]
