# Generated by Django 5.1.5 on 2025-01-18 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0004_remove_user_location_remove_user_region"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="certification_file",
        ),
        migrations.RemoveField(
            model_name="user",
            name="certification_type",
        ),
        migrations.RemoveField(
            model_name="user",
            name="pollution_certificate",
        ),
    ]
