# Generated by Django 5.0.8 on 2024-09-21 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_user_address_user_breadth_user_coopcapacity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='chick_count',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
