# Generated by Django 5.1.5 on 2025-01-19 04:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0005_remove_user_certification_file_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="address",
        ),
        migrations.RemoveField(
            model_name="user",
            name="expiry_date",
        ),
    ]
