# Generated by Django 5.0.8 on 2024-10-23 23:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_supplier_supplier_code_supplier_unique_supplier_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='coopcapacity',
        ),
        migrations.RemoveField(
            model_name='user',
            name='plan_file',
        ),
    ]
