# Generated by Django 5.1.1 on 2024-09-22 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_user_chick_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='chick_count',
        ),
    ]
