# Generated by Django 5.0.8 on 2024-10-23 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_remove_user_coopcapacity_remove_user_plan_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='coopcapacity',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='plan_file',
            field=models.FileField(blank=True, null=True, upload_to='farm_plan/'),
        ),
    ]
