# Generated by Django 5.1.5 on 2025-01-19 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0006_remove_user_address_remove_user_expiry_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="expiry_date",
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
