# Generated by Django 5.0.8 on 2024-09-27 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_remove_user_chick_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='breadth',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='length',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
    ]
