# Generated by Django 5.1.5 on 2025-01-19 05:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0007_user_expiry_date"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="expiry_date",
        ),
        migrations.RemoveField(
            model_name="user",
            name="hotel_license",
        ),
    ]
