# Generated by Django 5.0.8 on 2025-03-01 03:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_alter_contract_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='end_date',
            field=models.DateField(default=datetime.datetime(2026, 3, 1, 3, 50, 1, 365562, tzinfo=datetime.timezone.utc)),
        ),
    ]
