# Generated by Django 5.0.8 on 2025-02-06 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_remove_user_expiry_date_remove_user_hotel_license'),
    ]

    operations = [
        migrations.AddField(
            model_name='vaccine',
            name='current_stock',
            field=models.PositiveIntegerField(default=0, help_text='Current available stock'),
        ),
        migrations.AddField(
            model_name='vaccine',
            name='stock_status',
            field=models.CharField(choices=[('IN_STOCK', 'In Stock'), ('LOW_STOCK', 'Low Stock'), ('OUT_OF_STOCK', 'Out of Stock')], default='OUT_OF_STOCK', max_length=20),
        ),
    ]
