# Generated by Django 5.0.8 on 2024-10-05 12:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_supervisorstakeholderassignment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supervisorstakeholderassignment',
            name='stakeholder',
        ),
        migrations.AddField(
            model_name='supervisorstakeholderassignment',
            name='stakeholders',
            field=models.ManyToManyField(related_name='stakeholder_assignments', to=settings.AUTH_USER_MODEL),
        ),
    ]
