# Generated by Django 5.0.8 on 2025-02-07 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_vaccine_current_stock_vaccine_stock_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='vaccine',
            name='expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
