# Generated by Django 5.0.8 on 2024-11-05 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_user_hotel_license'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='hotel_license',
            field=models.FileField(blank=True, null=True, upload_to='hotel_licenses/'),
        ),
    ]
