# Generated by Django 5.0.8 on 2025-02-07 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_vaccine_expiry_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='vaccine',
            name='batch_number',
            field=models.CharField(blank=True, help_text='Vaccine batch number', max_length=50),
        ),
        migrations.AddField(
            model_name='vaccine',
            name='minimum_stock_level',
            field=models.PositiveIntegerField(default=100, help_text='Minimum stock level before warning'),
        ),
        migrations.AddField(
            model_name='vaccine',
            name='notes',
            field=models.TextField(blank=True),
        ),
    ]
