# Generated by Django 5.0.8 on 2025-03-01 04:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_alter_contract_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='end_date',
            field=models.DateField(default=datetime.datetime(2026, 3, 1, 4, 15, 16, 429910, tzinfo=datetime.timezone.utc)),
        ),
    ]
