# Generated by Django 5.0.8 on 2025-02-07 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_vaccine_batch_number_vaccine_minimum_stock_level_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vaccine',
            name='vaccination_day',
            field=models.IntegerField(choices=[(7, '7th Day'), (14, '14th Day'), (21, '21st Day')], default=7, help_text='Day of vaccination administration'),
        ),
    ]
