# Generated by Django 5.0.8 on 2025-02-07 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_vaccine_vaccination_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vaccine',
            name='vaccination_day',
            field=models.IntegerField(choices=[(7, '7th Day'), (14, '14th Day'), (21, '21st Day')], help_text='Day of vaccination administration'),
        ),
    ]
