# Generated by Django 5.0.8 on 2025-03-01 07:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_alter_contract_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='end_date',
            field=models.DateField(default=datetime.datetime(2026, 3, 1, 7, 1, 46, 533558, tzinfo=datetime.timezone.utc)),
        ),
    ]
