# Generated by Django 5.0.8 on 2025-02-10 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_alter_vaccine_vaccination_day'),
    ]

    operations = [
        migrations.CreateModel(
            name='BatchPerformanceBenchmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('performance_level', models.CharField(choices=[('EXCELLENT', 'Excellent'), ('GOOD', 'Good'), ('AVERAGE', 'Average'), ('POOR', 'Poor'), ('CRITICAL', 'Critical')], max_length=20)),
                ('min_weight', models.FloatField()),
                ('max_weight', models.FloatField()),
                ('min_fcr', models.FloatField()),
                ('max_fcr', models.FloatField()),
                ('min_temperature', models.FloatField()),
                ('max_temperature', models.FloatField()),
                ('min_humidity', models.FloatField()),
                ('max_humidity', models.FloatField()),
                ('min_feed_intake', models.FloatField()),
                ('max_feed_intake', models.FloatField()),
                ('min_water_consumption', models.FloatField()),
                ('max_water_consumption', models.FloatField()),
                ('max_mortality_rate', models.FloatField()),
            ],
            options={
                'ordering': ['performance_level'],
            },
        ),
    ]
