# Generated by Django 5.0.8 on 2025-03-01 10:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0014_alter_contract_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='end_date',
            field=models.DateField(default=datetime.datetime(2026, 3, 1, 10, 14, 31, 458618, tzinfo=datetime.timezone.utc)),
        ),
    ]
