# Generated by Django 5.0.8 on 2025-02-11 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0014_batchperformancebenchmark'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feed_type', models.CharField(choices=[('starter', 'Starter Feed (0-21 days)'), ('grower', 'Grower Feed (22-35 days)'), ('finisher', 'Finisher Feed (36+ days)')], max_length=20)),
                ('number_of_sacks', models.PositiveIntegerField(help_text='Number of 50kg sacks available')),
                ('price_per_sack', models.DecimalField(decimal_places=2, default=1750.0, help_text='Price for one 50kg sack', max_digits=8)),
                ('minimum_sacks', models.PositiveIntegerField(default=20, help_text='Minimum number of sacks to maintain')),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
