# Generated by Django 5.0.8 on 2025-03-02 06:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0015_alter_contract_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='end_date',
            field=models.DateField(default=datetime.datetime(2026, 3, 2, 6, 12, 52, 702532, tzinfo=datetime.timezone.utc)),
        ),
    ]
