# Generated by Django 5.0.8 on 2025-02-16 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0015_feedstock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vaccine',
            name='batch_number',
            field=models.CharField(blank=True, help_text='Vaccine batch number', max_length=50, null=True),
        ),
    ]
