# Generated by Django 5.0.8 on 2025-02-17 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0016_alter_vaccine_batch_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vaccine',
            name='batch_number',
            field=models.CharField(default=1, help_text='Vaccine batch number', max_length=50),
            preserve_default=False,
        ),
    ]
