# Generated by Django 5.0.8 on 2025-02-17 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0017_alter_vaccine_batch_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vaccine',
            name='batch_number',
            field=models.CharField(blank=True, help_text='Vaccine batch number', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='vaccine',
            name='doses_required',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
