# Generated by Django 5.0.8 on 2025-03-05 04:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0017_alter_contract_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='end_date',
            field=models.DateField(default=datetime.datetime(2026, 3, 5, 3, 59, 8, 51866, tzinfo=datetime.timezone.utc)),
        ),
    ]
