# Generated by Django 5.0.8 on 2025-02-22 18:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0018_alter_vaccine_batch_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_number', models.CharField(max_length=50, unique=True)),
                ('contract_terms', models.TextField()),
                ('admin_signature_path', models.CharField(blank=True, max_length=255, null=True)),
                ('stakeholder_signature_path', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(default='Pending', max_length=20)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('signed_date', models.DateTimeField(blank=True, null=True)),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_contracts', to=settings.AUTH_USER_MODEL)),
                ('stakeholder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stakeholder_contracts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
