# Generated by Django 5.0.8 on 2025-03-09 04:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0018_alter_contract_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='end_date',
            field=models.DateField(default=datetime.datetime(2026, 3, 9, 4, 42, 36, 543783, tzinfo=datetime.timezone.utc)),
        ),
    ]
