# Generated by Django 5.0.8 on 2025-03-09 12:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0019_alter_contract_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='end_date',
            field=models.DateField(default=datetime.datetime(2026, 3, 9, 12, 33, 59, 939308, tzinfo=datetime.timezone.utc)),
        ),
    ]
