# Generated by Django 5.0.8 on 2025-02-23 04:26

import datetime
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0019_contract'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contract',
            old_name='signed_date',
            new_name='stakeholder_signed_date',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='admin_signature_path',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='stakeholder_signature_path',
        ),
        migrations.AddField(
            model_name='contract',
            name='additional_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='admin_signature',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='admin_signed_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='contract_type',
            field=models.CharField(choices=[('Standard', 'Standard Contract'), ('Premium', 'Premium Contract'), ('Special', 'Special Agreement')], default='Standard', max_length=50),
        ),
        migrations.AddField(
            model_name='contract',
            name='end_date',
            field=models.DateField(default=datetime.datetime(2026, 2, 23, 4, 25, 53, 279739, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AddField(
            model_name='contract',
            name='last_modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='stakeholder_signature',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='contract',
            name='contract_number',
            field=models.CharField(default=uuid.uuid4, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='contract',
            name='contract_terms',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='contract',
            name='status',
            field=models.CharField(choices=[('Draft', 'Draft'), ('Pending_Admin', 'Pending Admin Signature'), ('Pending_Stakeholder', 'Pending Stakeholder Signature'), ('Active', 'Active'), ('Expired', 'Expired'), ('Terminated', 'Terminated')], default='Draft', max_length=20),
        ),
    ]
