# Generated by Django 5.0.8 on 2025-03-09 14:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0020_alter_contract_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='end_date',
            field=models.DateField(default=datetime.datetime(2026, 3, 9, 14, 46, 39, 945422, tzinfo=datetime.timezone.utc)),
        ),
    ]
