# Generated by Django 5.0.8 on 2025-03-10 14:50

import datetime
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0021_alter_contract_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='end_date',
            field=models.DateField(default=datetime.datetime(2026, 3, 10, 14, 50, 46, 538299, tzinfo=datetime.timezone.utc)),
        ),
        migrations.CreateModel(
            name='OrderAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('total_orders', models.IntegerField(default=0)),
                ('total_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('one_kg_count', models.IntegerField(default=0)),
                ('two_kg_count', models.IntegerField(default=0)),
                ('three_kg_count', models.IntegerField(default=0)),
                ('cash_payments', models.IntegerField(default=0)),
                ('online_payments', models.IntegerField(default=0)),
                ('upi_payments', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Order Analytics',
                'indexes': [models.Index(fields=['date'], name='user_ordera_date_537609_idx')],
            },
        ),
    ]
