# Generated by Django 5.0.8 on 2025-02-24 06:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0022_alter_contract_end_date_chatmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='chat_attachments/'),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='attachment_type',
            field=models.CharField(blank=True, choices=[('image', 'Image'), ('document', 'Document'), ('audio', 'Audio')], max_length=20),
        ),
        migrations.AlterField(
            model_name='contract',
            name='end_date',
            field=models.DateField(default=datetime.datetime(2026, 2, 24, 6, 20, 51, 631249, tzinfo=datetime.timezone.utc)),
        ),
    ]
