# Generated by Django 5.0.8 on 2025-03-10 15:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0022_alter_contract_end_date_orderanalytics'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='end_date',
            field=models.DateField(default=datetime.datetime(2026, 3, 10, 15, 51, 17, 907823, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='orderanalytics',
            name='date',
            field=models.DateField(),
        ),
    ]
