# Generated by Django 5.0.8 on 2025-03-10 16:00

import datetime
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0023_alter_contract_end_date_alter_orderanalytics_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='end_date',
            field=models.DateField(default=datetime.datetime(2026, 3, 10, 16, 0, 16, 933912, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='orderanalytics',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
