# Generated by Django 5.0.8 on 2025-02-24 08:58

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stakeholder', '0042_alter_farm_coopcapacity'),
        ('user', '0023_chatmessage_attachment_chatmessage_attachment_type_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='chatroom',
            unique_together={('admin', 'stakeholder')},
        ),
        migrations.AddField(
            model_name='chatroom',
            name='farm',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='farm_chats', to='stakeholder.farm'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='end_date',
            field=models.DateField(default=datetime.datetime(2026, 2, 24, 8, 57, 56, 335429, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterUniqueTogether(
            name='chatroom',
            unique_together={('admin', 'stakeholder'), ('farm',)},
        ),
    ]
