# Generated by Django 5.0.8 on 2025-02-24 09:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0024_alter_chatroom_unique_together_chatroom_farm_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='end_date',
            field=models.DateField(default=datetime.datetime(2026, 2, 24, 9, 8, 50, 571856, tzinfo=datetime.timezone.utc)),
        ),
    ]
