# Generated by Django 5.0.8 on 2025-02-24 09:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stakeholder', '0042_alter_farm_coopcapacity'),
        ('user', '0025_alter_contract_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='end_date',
            field=models.DateField(default=datetime.datetime(2026, 2, 24, 9, 46, 15, 465683, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterUniqueTogether(
            name='chatroom',
            unique_together={('admin', 'stakeholder', 'farm')},
        ),
    ]
