# Generated by Django 5.0.8 on 2025-03-11 04:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0025_alter_contract_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='end_date',
            field=models.DateField(default=datetime.datetime(2026, 3, 11, 4, 10, 13, 885528, tzinfo=datetime.timezone.utc)),
        ),
    ]
