# Generated by Django 5.0.8 on 2025-02-24 09:59

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stakeholder', '0042_alter_farm_coopcapacity'),
        ('user', '0026_alter_contract_end_date_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='chatroom',
            unique_together={('admin', 'farm', 'other_farm')},
        ),
        migrations.AddField(
            model_name='chatroom',
            name='other_farm',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='other_farm_chats', to='stakeholder.farm'),
        ),
        migrations.AddField(
            model_name='chatroom',
            name='room_type',
            field=models.CharField(choices=[('admin_farm', 'Admin to Farm'), ('farm_farm', 'Farm to Farm')], default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contract',
            name='end_date',
            field=models.DateField(default=datetime.datetime(2026, 2, 24, 9, 58, 43, 388901, tzinfo=datetime.timezone.utc)),
        ),
        migrations.RemoveField(
            model_name='chatroom',
            name='stakeholder',
        ),
    ]
