# Generated by Django 5.0.8 on 2025-02-24 10:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0027_alter_chatroom_unique_together_chatroom_other_farm_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='chatroom',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='contract',
            name='end_date',
            field=models.DateField(default=datetime.datetime(2026, 2, 24, 10, 5, 5, 698927, tzinfo=datetime.timezone.utc)),
        ),
    ]
