# Generated by Django 5.0.8 on 2025-03-11 07:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0027_alter_contract_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='end_date',
            field=models.DateField(default=datetime.datetime(2026, 3, 11, 7, 0, 15, 64137, tzinfo=datetime.timezone.utc)),
        ),
    ]
