# Generated by Django 5.0.8 on 2025-03-13 04:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0028_alter_contract_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='end_date',
            field=models.DateField(default=datetime.datetime(2026, 3, 13, 4, 49, 54, 661936, tzinfo=datetime.timezone.utc)),
        ),
    ]
