# Generated by Django 5.0.8 on 2025-02-24 10:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stakeholder', '0042_alter_farm_coopcapacity'),
        ('user', '0028_alter_chatroom_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='end_date',
            field=models.DateField(default=datetime.datetime(2026, 2, 24, 10, 9, 50, 297440, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AddIndex(
            model_name='chatroom',
            index=models.Index(fields=['admin', 'farm', 'other_farm'], name='chat_room_composite_idx'),
        ),
    ]
