# Generated by Django 5.0.8 on 2025-02-24 11:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0029_alter_contract_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='end_date',
            field=models.DateField(default=datetime.datetime(2026, 2, 24, 11, 14, 20, 411168, tzinfo=datetime.timezone.utc)),
        ),
    ]
