# Generated by Django 5.0.8 on 2025-02-24 11:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0031_alter_contract_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='end_date',
            field=models.DateField(default=datetime.datetime(2026, 2, 24, 11, 32, 26, 635496, tzinfo=datetime.timezone.utc)),
        ),
    ]
