# Generated by Django 5.0.8 on 2025-02-25 03:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0034_alter_contract_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='end_date',
            field=models.DateField(default=datetime.datetime(2026, 2, 25, 3, 43, 26, 828998, tzinfo=datetime.timezone.utc)),
        ),
        migrations.DeleteModel(
            name='ChatMessage',
        ),
    ]
