# Generated by Django 5.0.8 on 2025-02-25 03:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0035_alter_contract_end_date_delete_chatmessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='end_date',
            field=models.DateField(default=datetime.datetime(2026, 2, 25, 3, 44, 52, 698206, tzinfo=datetime.timezone.utc)),
        ),
        migrations.DeleteModel(
            name='ChatRoom',
        ),
    ]
