# Generated by Django 5.0.8 on 2025-02-26 14:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0037_alter_contract_end_date_chatroom_chatmessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='end_date',
            field=models.DateField(default=datetime.datetime(2026, 2, 26, 14, 34, 17, 239211, tzinfo=datetime.timezone.utc)),
        ),
    ]
